# Generated by Django 6.0.7 on 2026-07-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='admin_password',
            field=models.CharField(default='admin123', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='admin_username',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
