# Generated by Django 6.0.7 on 2026-08-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_officer_student_is_first_login_student_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(default='BS Computer Science', max_length=100),
        ),
    ]
